global using CryptoCurrencyRecommendations.Api.Helpers;
global using CryptoCurrencyRecommendations.Api.Extensions;
global using CryptoCurrencyRecommendations.Services.Dtos;
global using CryptoCurrencyRecommendations.Domain.interfaces;
global using CryptoCurrencyRecommendations.Services;